### ISSUE TITLE
Transaction screen issues

### ISSUE THREAD

**Issue by 0xc1c4da** [status-im/token#16]
- [x] 1. lets make this a field that can be selected/copied but un-editable
- [x] 2. remove copy, show qr & backup / restore, these have all moved to other places now.
- [x] 3. Transaction list should have empty placeholder "No transactions found" center aligned (similar to how "backup & restore account" is)
- [x] 4. url changes to address? it shouldn't do that

**Comment by 0xc1c4da** [comment]
same issues in `develop` branch, reopening 
<img width=320 src=https://cloud.githubusercontent.com/assets/2714786/19387374/6bca7510-924c-11e6-96fb-63ec3c4e7e68.png />

**Comment by alwx** [comment]
https://github.com/status-im/wallet/pull/20
