### ISSUE TITLE
wallet screen is vertically scrollable

### ISSUE THREAD

**Issue by 0xc1c4da** [status-im/token#19]
- [ ] the spacing between cards and "Wallets" header is messed up
- [x] hide trade eth / create a wallet for now

![scrolling-disco](https://cloud.githubusercontent.com/assets/2714786/19387268/b190da40-924b-11e6-8dc5-68b834879a35.gif)

**Comment by 0xc1c4da** [comment]
i see the padding changed but there is also the second checkbox here for hiding "trade eth" & "create a wallet"

**Comment by alwx** [comment]
https://github.com/status-im/wallet/pull/20
